import fs from 'node:fs';
import path from 'node:path';
const [asrDir, audioPath, outPath] = process.argv.slice(2);
const {pipeline, env} = await import(path.join(asrDir, 'node_modules/@huggingface/transformers/dist/transformers.node.mjs'));
env.allowRemoteModels = false;
env.localModelPath = path.join(asrDir, 'node_modules/sts-whisper-small/models') + '/';
const asr = await pipeline('automatic-speech-recognition', 'Xenova/whisper-small', {dtype: 'q8', device: 'cpu'});
const buf = fs.readFileSync(audioPath);
const audio = new Float32Array(buf.buffer, buf.byteOffset, buf.byteLength / 4);
const t0 = Date.now();
const out = await asr(audio, {language: 'french', task: 'transcribe', return_timestamps: 'word', chunk_length_s: 30, stride_length_s: 5});
fs.writeFileSync(outPath, JSON.stringify(out, null, 1));
console.log('done in', (Date.now() - t0) / 1000, 's');
console.log(out.text);
